name: chocolatine

permissions:
  contents: read

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  MIRROR_SSH_URL: ${{ vars.MIRROR_SSH_URL }}
  EXECUTABLES: ${{ vars.EXECUTABLES }}

jobs:
  check_compilation_and_coding_style:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:Flavio-KOUGBADI/Radar-Epitech-Project.git
          ssh_private_key:
            ${{ secrets.SSH_KEY }}

      - name: Checkout repository
        run: banana-check-repo

      - name: compile with make
        run: make
        timeout-minutes: 2
        env:
          CC: epiclang
